### ISSUE TITLE
eltwise_layer.cpp:34] Check failed: bottom[0]->shape() == bottom[i]->shape() bottom[0]: 1 48 65 33 (102960), 

### ISSUE THREAD

**Issue by ouxiand** [jiangtaoo2333/onnx2caffe#1]
20:05:51.686959 9912 eltwise_layer.cpp:34] Check failed: bottom[0]->shape() == bottom[i]->shape() bottom[0]: 1 48 65 33 (102960), bottom[1]: 1 48 62 30 (89280)
*** Check failure stack trace: ***
已放弃 (核心已转储) 
May I ask how to solve it?

**Comment by jiangtaoo2333** [comment]
> 

did u use sigmoid  in this layer?

**Comment by ouxiand** [comment]
![image](https://github.com/jiangtaoo2333/onnx2caffe/assets/95113887/dc13d59d-51a5-468a-8b6f-4dd11c36fc48)
Like this，Is this okay？

**Comment by ouxiand** [comment]
[osnet_x0_75_msmt17_combineall_2.zip](https://github.com/jiangtaoo2333/onnx2caffe/files/11641760/osnet_x0_75_msmt17_combineall_2.zip)
Can you help with the analysis?

**Comment by ouxiand** [comment]
@jiangtaoo2333   hello  Can you help with the analysis?

**Comment by jiangtaoo2333** [comment]
> @jiangtaoo2333 hello Can you help with the analysis?

ok,i will check this prototxt,maybe layter.

**Comment by ouxiand** [comment]
May I ask if you have found any ideas?    The conversion of the ONNX export operator version from 9 to 15 to the Caffe model is all the same error, but I am certain that the ONNX run result is correct.

**Comment by ouxiand** [comment]
@jiangtaoo2333   Hello ,can you help me? I have been stuck with this bug for over two weeks

**Comment by jiangtaoo2333** [comment]
[](url)

**Comment by jiangtaoo2333** [comment]
[osnet_x0_75_msmt17_combineall_2_sim (2).zip](https://github.com/jiangtaoo2333/onnx2caffe/files/11699269/osnet_x0_75_msmt17_combineall_2_sim.2.zip)
@ouxiand I have been on a business trip recently. Can you check if the following model is correct?

**Comment by ouxiand** [comment]
Thank you for your support and I'm sorry to bother you. The caffe result was correct. How did you handle it?
